name: CI

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 30
   
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - name: Checkout
        uses: actions/checkout@v2

      # https://pnpm.io/continuous-integration#github-actions
      - name: Install Pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.7

      # Installs Node.js.
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Compile
        run: pnpm run compile
      
      - name: Buid plugins
        run: pnpm run build-plugins

      - name: Run tests
        run: pnpm test
      
      - name: Build browser
        run: pnpm run build-browser

      - name: Build Electron
        env:
          BUILD_PARENT_DIR: c:\temp
        run: pnpm run build-electron-win
